plugins {
    id 'com.android.application'
}

android {
    namespace 'com.megamobile.game'
    compileSdk 35

    defaultConfig {
        applicationId 'com.megamobile.game'
        minSdk 26
        targetSdk 29
        versionCode 4
        versionName '0.3.1'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
