plugins { id 'com.android.application' }

android {
    namespace 'com.megamobile.game'
    compileSdk 35

    defaultConfig {
        applicationId 'com.megamobile.game'
        minSdk 26
        targetSdk 29
        versionCode 11
        versionName '0.8.0'
    }

    buildTypes {
        release { minifyEnabled false }
        debug { debuggable true }
    }

    lint {
        disable 'ExpiredTargetSdkVersion'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
