package com.healthcoach.app
import android.content.Context
import androidx.health.connect.client.HealthConnectClient
import androidx.health.connect.client.permission.HealthPermission
import androidx.health.connect.client.records.*
import androidx.health.connect.client.request.ReadRecordsRequest
import androidx.health.connect.client.time.TimeRangeFilter
import java.time.*
class HealthReader(c:Context){private val client=HealthConnectClient.getOrCreate(c)
val permissions=setOf(HealthPermission.getReadPermission(SleepSessionRecord::class),HealthPermission.getReadPermission(HeartRateRecord::class),HealthPermission.getReadPermission(RestingHeartRateRecord::class),HealthPermission.getReadPermission(HeartRateVariabilityRmssdRecord::class),HealthPermission.getReadPermission(RespiratoryRateRecord::class),HealthPermission.getReadPermission(StepsRecord::class),HealthPermission.getReadPermission(DistanceRecord::class),HealthPermission.getReadPermission(ExerciseSessionRecord::class))
suspend fun allowed()=client.permissionController.getGrantedPermissions().containsAll(permissions)
suspend fun snapshot():Snapshot{val now=Instant.now();val f=TimeRangeFilter.between(now.minus(Duration.ofDays(100)),now);val sleeps=client.readRecords(ReadRecordsRequest(SleepSessionRecord::class,f)).records;val resting=client.readRecords(ReadRecordsRequest(RestingHeartRateRecord::class,f)).records;val hrv=client.readRecords(ReadRecordsRequest(HeartRateVariabilityRmssdRecord::class,f)).records;val resp=client.readRecords(ReadRecordsRequest(RespiratoryRateRecord::class,f)).records;val steps=client.readRecords(ReadRecordsRequest(StepsRecord::class,f)).records;val dist=client.readRecords(ReadRecordsRequest(DistanceRecord::class,f)).records;return Snapshot.make(sleeps,resting,hrv,resp,steps,dist)}}
data class Day(val date:String,val sleep:Int?,val light:Int?,val deep:Int?,val rem:Int?,val resting:Double?,val hrv:Double?,val resp:Double?,val steps:Long,val distance:Double)
data class Snapshot(val generatedAt:String,val sleepStart:String?,val sleepEnd:String?,val days:List<Day>){companion object{fun make(s:List<SleepSessionRecord>,r:List<RestingHeartRateRecord>,h:List<HeartRateVariabilityRmssdRecord>,rr:List<RespiratoryRateRecord>,st:List<StepsRecord>,di:List<DistanceRecord>):Snapshot{val z=ZoneId.systemDefault();val today=LocalDate.now(z);fun<T>v(l:List<T>,d:LocalDate,t:(T)->Instant,x:(T)->Double)=l.filter{t(it).atZone(z).toLocalDate()==d}.maxByOrNull{t(it)}?.let(x);val days=(0L..89L).map{n->val d=today.minusDays(n);val sl=s.filter{it.endTime.atZone(z).toLocalDate()==d}.maxByOrNull{it.endTime};var li=0;var de=0;var re=0;sl?.stages?.forEach{q->val m=Duration.between(q.startTime,q.endTime).toMinutes().toInt();when(q.stage){SleepSessionRecord.STAGE_TYPE_LIGHT->li+=m;SleepSessionRecord.STAGE_TYPE_DEEP->de+=m;SleepSessionRecord.STAGE_TYPE_REM->re+=m}};Day(d.toString(),sl?.let{Duration.between(it.startTime,it.endTime).toMinutes().toInt()},li.takeIf{sl!=null},de.takeIf{sl!=null},re.takeIf{sl!=null},v(r,d,{it.time},{it.beatsPerMinute}),v(h,d,{it.time},{it.heartRateVariabilityMillis}),v(rr,d,{it.time},{it.rate}),st.filter{it.endTime.atZone(z).toLocalDate()==d}.sumOf{it.count},di.filter{it.endTime.atZone(z).toLocalDate()==d}.sumOf{it.distance.inMeters})};val last=s.maxByOrNull{it.endTime};return Snapshot(Instant.now().toString(),last?.startTime?.toString(),last?.endTime?.toString(),days)}}}